### ISSUE TITLE
Mismatch between depth and rgb camera. 

### ISSUE THREAD

**Issue by JD-ETH** [MIT-TESSE/tesse-gym#7]
From the camera information inside the gym: 
```
>>> from tesse.env import Env
>>> from tesse.msgs import CameraInformationRequest
>>> env = Env()
>>> camera_params = env.request(CameraInformationRequest())
>>> print(camera_params.metadata)

<TESSE_Agent_CameraInfo_v0.5>
  <camera_info>
    <name>rgb_left</name>
    <id>0</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>rgb_right</name>
    <id>1</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>segmentation</name>
    <id>2</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>depth</name>
    <id>3</id>
    <parameters height='240' width='320' fov='50'/>
    <position x='-0.05' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
  <camera_info>
    <name>3pv</name>
    <id>4</id>
    <parameters height='240' width='320' fov='90'/>
    <position x='0' y='0.7' z='-1.2'/>
    <rotation x='0.1100685' y='0' z='0' w='0.993924'/>
    <draw_distance near='0.3' far='150'/>
  </camera_info>
  <camera_info>
    <name>instance_segmentation</name>
    <id>5</id>
    <parameters height='240' width='320' fov='60'/>
    <position x='0.05000019' y='0' z='0'/>
    <rotation x='0' y='0' z='0' w='1'/>
    <draw_distance near='0.05' far='50'/>
  </camera_info>
</TESSE_Agent_CameraInfo_v0.5>
```
1. The depth and 3pv camera has a different field of view than the rest. Indeed, the depth image appears narrower then the rgb image side by side.  Is this intentional? Can this be changed to be the same? I need to correlated the two images pixel by pixel. 

2. I am trying to interpret the depth image data. It is returning a number way lesser than 1. Does this mean the actual distance correspond to `d*(draw_distance.far)`? so 0.2 will correspond to 10 meters? 

3. Also i need to infer the camera parameters. Just to confirm, the FOV is only horizontal right?

**Comment by JD-ETH** [comment]
This is apparent when overlaying the 2D depth and rgv image together to get a pointcloud: 
The right fruit doesn't get the red color. 
![rendered-cloud](https://user-images.githubusercontent.com/23099791/79001553-f23d7180-7b4e-11ea-862d-435811aeabb3.png)

**Comment by ZacRavichandran** [comment]
1. Currently, the default depth camera FOV is 50 degrees while the rest of the agent's cameras (stereo and segmentation) have a FOV of 60 degrees. In a release that we'll publish next week, this is fixed so that all cameras have a FOV of 60 degrees. The 3pv view is only meant for visualization, so that will remain the same. 

In the meantime, the depth camera can be synchronized through either:

A. [`SetCameraParametersRequest`](https://github.com/MIT-TESSE/tesse-interface/blob/master/src/tesse/msgs.py#L247) in [`tesse-interface`](https://github.com/MIT-TESSE/tesse-interface):

```python
from tesse.msgs import SetCameraParametersRequest, Camera
from tesse.env import Env

Env().request(SetCameraParametersRequest(Camera.DEPTH, height_in_pixels=240, width_in_pixels=320, field_of_view=60, near_clip_plane=0.05))
```

B. [`set_all_camera_params`](https://github.com/MIT-TESSE/tesse-gym/blob/master/src/tesse_gym/core/utils.py#L76) in `tesse_gym`, which will synchronize all cameras when the  simulator(s) start. To use, pass that method to the `init_hook` parameter of a gym environment. In the baseline example, this would look as follows: 

```python
from tesse_gym.core.utils import set_all_camera_params
...

env = GoSeekFullPerception(
                str(filename),
                network_config=get_network_config(worker_id=rank),
                n_targets=n_targets,
                episode_length=episode_length,
                scene_id=scene_id[rank],
                target_found_reward=target_found_reward,
                init_hook=set_all_camera_params
            )
```

2. Yep, the depth image is scaled to a range of `[0, 1]`. To recover depth in meters, multiply by `draw_distance.far`.

3. The FOV is only vertical. The horizontal FOV can then be inferred by:

```sh
camera_width / camera_height * vertical_fov
```

**Comment by JD-ETH** [comment]
Thanks a lot for the answer! @ZacRavichandran 

Two things to point out in your answer: 
1. Solution 1  needs to be done once for every environment. So if there is more than one environment being used in the training, one needs to to specify the port it communicates to. 
2. Without specifying `step_rate=20,` inside `GoSeekFullPerception` could lead to networking issues.
